load_sequence:         12
target_model:          "Circulation::PickUpRequest"
target_adapter:        "google_sheet"
file_id:               <%= ENV["SPRING_STATS_FILE_ID"] %>
truncate_before_load:  "no"
sheet_name:            "Lewis"
header_rows_to_skip:   2
column_mappings: 
  location: "Lewis Library"
  received: "%{your_location_requests_received}"
  local_processed: "%{your_location_requests_processed_for_pickup}"
  offsite_processed: "%{re_cap_or_annex_reqs_processed_for_pickup}"
  abandoned: "%{reshelved_locally_or_returned_to_re_cap_annex_because_not_picked_up}"